sudo: false
language: go
go:
  - 1.9
  - 1.9.1
  - 1.9.2
  - 1.9.3
before_install:
  - go get -t -v ./...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=auth.coverprofile
  - go test -coverprofile=jwt.coverprofile ./jwt
  - go test -coverprofile=ed25519.coverprofile ./jwt/ed25519
  - gover
  - go tool cover -html=gover.coverprofile
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
