sudo: false
language: go
go:
  - 1.7
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=gear-auth.coverprofile
  - goveralls -coverprofile=gear-auth.coverprofile -service=travis-ci
