sudo: false
language: go
go:
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.8.4
  - 1.8.5
  - 1.9
  - 1.9.1
  - 1.9.2
before_install:
  - go get -t -v ./...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=auth.coverprofile
  - go test -coverprofile=jwt.coverprofile ./jwt
  - gover
  - go tool cover -html=gover.coverprofile
  - goveralls -coverprofile=gover.coverprofile -service=travis-ci
